---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure DNS.
- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
